### ISSUE TITLE
Error while evaluating ICDAR13 Images - Expected Ptr<cv::UMat> for argument 'img'

### ISSUE THREAD

**Issue by mohammedayub44** [clovaai/CRAFT-pytorch#140]
Hi,

I ran into an error while evaluating the pretrained model available from your repository on ICDAR13 images.

```bash
Test image 159/233: /home/ubuntu/mayub/text_detection/TedEval/data/icdar2013test_img/img_39.jpg
infer/postproc time : 55.896/0.122
Traceback (most recent call last):
  File "test.py", line 169, in <module>
    file_utils.saveResult(image_path, image[:,:,::-1], polys, dirname=result_folder)
  File "/home/ubuntu/mayub/text_detection/CRAFT-pytorch/file_utils.py", line 62, in saveResult
    cv2.polylines(img, [poly.reshape((-1, 1, 2))], True, color=(0, 0, 255), thickness=2)
TypeError: Expected Ptr<cv::UMat> for argument 'img'
```
Looks like it's complaining about image not being an array.
I checked the code `saveResult()` function and we do convert it to an arrary `img = np.array(img)`. I also checked the source image, looks fine its slightly high res (3888x2592).

Not sure why it is throwing this error. 

FYI -
numpy - 1.19.5
torch - 1.1.0 
torchvision - 0.3.0

Any help appreciated. Thanks !

**Comment by mohammedayub44** [comment]
Figured it out. Had to make a copy of the image so that it can be modified. 

See here: https://github.com/opencv/opencv/issues/18120#issuecomment-727526739
