### ISSUE TITLE
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5,) + inhomogeneous part.

### ISSUE THREAD

**Issue by HardikJain02** [clovaai/CRAFT-pytorch#194]
I crash into this error while executing 
python test.py --trained_model=craft_mlt_25k.pth --refiner_model=craft_refiner_CTW1500.pth --test_folder=myfolder --refine

Traceback (most recent call last):
  File "C:\code\CRAFT-pytorch\test.py", line 165, in <module>
    bboxes, polys, score_text = test_net(net, image, args.text_threshold, args.link_threshold, args.low_text, args.cuda, args.poly, refine_net)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\code\CRAFT-pytorch\test.py", line 106, in test_net
    polys = craft_utils.adjustResultCoordinates(polys, ratio_w, ratio_h)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\code\CRAFT-pytorch\craft_utils.py", line 251, in adjustResultCoordinates
    polys = np.array(polys)
            ^^^^^^^^^^^^^^^
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5,) + inhomogeneous part.

**Comment by HardikJain02** [comment]
GPT fixed the issue for now:

`def adjustResultCoordinates(polys, ratio_w, ratio_h, ratio_net=2):
    if len(polys) > 0:
        for k in range(len(polys)):
            if polys[k] is not None:
                polys[k] *= np.array([ratio_w * ratio_net, ratio_h * ratio_net])
    return polys`

Any better solution?

**Comment by dungviet112** [comment]
I changed numpy version to `1.23.0` and it worked for me

**Comment by HordesOfGhost** [comment]
def adjustResultCoordinates(polys, ratio_w, ratio_h, ratio_net=2):
    if len(polys) > 0:
        polys_filtered = [poly for poly in polys if poly is not None] # Added line
        polys = np.array(polys_filtered)
        for k in range(len(polys)):
            if polys[k] is not None:
                polys[k] *= (ratio_w * ratio_net, ratio_h * ratio_net)
    return polys
    
    replace this code in "site-packages\craft_text_detector\craft_utils.py" to handle the inhomogeneous array problem.

**Comment by HordesOfGhost** [comment]
`def adjustResultCoordinates(polys, ratio_w, ratio_h, ratio_net=2):
    if len(polys) > 0:
        polys_filtered = [poly for poly in polys if poly is not None] # Added Line
        polys = np.array(polys_filtered) 
        for k in range(len(polys)):
            if polys[k] is not None:
                polys[k] *= (ratio_w * ratio_net, ratio_h * ratio_net)
    return polys
`
Replace the above code in site-packages\craft_text_detector\craft_utils.py to solve the inhomogeneous array problem.
